//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        public int AdId { get; set; }
        public string ImageURL { get; set; }
        public string ThumbnailURL { get; set; }
        public string LinkURL { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string City { get; set; }
        public string Recordstatus { get; set; }
    }
}
