//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupons
    {
        public int Id { get; set; }
        public string EventName { get; set; }
        public string CouponCode { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public string TicketCategory { get; set; }
    }
}
