//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int EventID { get; set; }
        public string SeatGeek_TourID { get; set; }
        public string HashTag { get; set; }
        public string TourDateID { get; set; }
        public string EventName { get; set; }
        public string VenueName { get; set; }
        public string Main_Genre { get; set; }
        public string Datetime_Local { get; set; }
        public string EventDate { get; set; }
        public string ArtistName { get; set; }
        public string VenueCountry { get; set; }
        public string VenueCity { get; set; }
        public string AttendingCount { get; set; }
        public string TicketsAvailable { get; set; }
        public string HotTour { get; set; }
        public string IsDeleted { get; set; }
    }
}
