//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportBulkTicket
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Section { get; set; }
        public string Row { get; set; }
        public string Seat { get; set; }
        public string Price { get; set; }
        public string order { get; set; }
        public string BarCode { get; set; }
        public Nullable<bool> TicketStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
