//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicSource
    {
        public int SourceID { get; set; }
        public int UserID { get; set; }
        public string Source { get; set; }
        public string SourceLink { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> MsourceID { get; set; }
        public string DeviceType { get; set; }
    }
}
