//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentStatus
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string PaymentResponse { get; set; }
        public string PaymentType { get; set; }
        public string TransactionId { get; set; }
        public string OrderNum { get; set; }
        public Nullable<bool> IsPaymentSucess { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> TourDateID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Cost { get; set; }
        public string Apartment { get; set; }
    }
}
