//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketingEventTickets
    {
        public int TicketId { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<System.Guid> TicketNumber { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
        public string TicketType { get; set; }
        public Nullable<System.DateTime> CheckInDateTime { get; set; }
    }
}
