//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketingInventoryNew
    {
        public int TicketId { get; set; }
        public Nullable<int> TourDateId { get; set; }
        public Nullable<int> TotalSeats { get; set; }
        public Nullable<bool> InAppTicketing { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDatet { get; set; }
        public string RecordStatus { get; set; }
    }
}
