//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourPhoto
    {
        public int TourPhotoID { get; set; }
        public int ArtistID { get; set; }
        public string TourName { get; set; }
        public string ImageThumbnailURL { get; set; }
        public string ImageURL { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string RecordStatus { get; set; }
        public string InstagramPostId { get; set; }
        public int TourDateId { get; set; }
    }
}
