//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSettings
    {
        public int UserSettingId { get; set; }
        public Nullable<long> UserID { get; set; }
        public string SettingKey { get; set; }
        public Nullable<bool> SettingValue { get; set; }
        public Nullable<int> NotificationCount { get; set; }
    }
}
