//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDevices
    {
        public int UserDeviceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string DeviceType { get; set; }
        public string DeviceToken { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
