//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtcTimeZone
    {
        public string CC { get; set; }
        public Nullable<double> Coordinates { get; set; }
        public string TZ { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> UTCoffset { get; set; }
        public Nullable<decimal> UTCDSToffset { get; set; }
        public string Notes { get; set; }
        public int TimezoneID { get; set; }
    }
}
