//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public int VenueID { get; set; }
        public string SeatGeek_VenuID { get; set; }
        public string VenueName { get; set; }
        public string ImageURL { get; set; }
        public string Extended_Address { get; set; }
        public string Display_Location { get; set; }
        public string Slug { get; set; }
        public string Postal_Code { get; set; }
        public string Address { get; set; }
        public string Timezone { get; set; }
        public string VenueCity { get; set; }
        public string VenueState { get; set; }
        public string VenueCountry { get; set; }
        public Nullable<decimal> VenueLat { get; set; }
        public Nullable<decimal> VenueLong { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string RecordStatus { get; set; }
        public string Eventful_VenueID { get; set; }
    }
}
